using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TheBookStore.Models
{
    public class FakeProductRepository : IProductRepository
    {
        public IQueryable<Product> Products => new List<Product>
        {
            new Product { Name = "Ведьмак", Description = "Фэнтези книга по вселенной ведьмака",
                        Price = 500, Category = "Фэнтези", Language = "Русский", Age = 50,
                        Author = "Анджей Сапковский", Size = "200x450", PageCount = 1460, Rate = 3.6,
                        DateCreate = DateTime.Now.AddHours(4) },
            new Product { Name = "Ведьмак", Description = "Фэнтези книга по вселенной ведьмака",
                        Price = 24, Category = "Фантастика", Language = "Русский", Age = 18,
                        Author = "Анджей Сапковский", Size = "200x450", PageCount = 234, Rate = 4.5,
                        DateCreate = DateTime.Now.AddHours(1) },
            new Product { Name = "Ведьмак", Description = "Фэнтези книга по вселенной ведьмака",
                        Price = 234, Category = "Драма", Language = "Русский", Age = 10,
                        Author = "Анджей Сапковский", Size = "200x450", PageCount = 2525, Rate = 4.3,
                        DateCreate = DateTime.Now.AddHours(2) },
            new Product { Name = "Ведьмак", Description = "Фэнтези книга по вселенной ведьмака",
                        Price = 423, Category = "Наука", Language = "Русский", Age = 14,
                        Author = "Анджей Сапковский", Size = "200x450", PageCount = 1212, Rate = 7.8,
                        DateCreate = DateTime.Now.AddHours(2) },
            new Product { Name = "Ведьмак", Description = "Фэнтези книга по вселенной ведьмака",
                        Price = 434, Category = "Детективы", Language = "Русский", Age = 12,
                        Author = "Анджей Сапковский", Size = "200x450", PageCount = 4535, Rate = 9.5,
                        DateCreate = DateTime.Now.AddHours(5) },
            new Product { Name = "Ведьмак", Description = "Фэнтези книга по вселенной ведьмака",
                        Price = 275, Category = "Эпос", Language = "Русский", Age = 16,
                        Author = "Анджей Сапковский", Size = "200x450", PageCount = 1214, Rate = 6.7,
                        DateCreate = DateTime.Now.AddHours(1) },
            new Product { Name = "Ведьмак", Description = "Фэнтези книга по вселенной ведьмака",
                        Price = 500, Category = "Фэнтези", Language = "Русский", Age = 50,
                        Author = "Анджей Сапковский", Size = "200x450", PageCount = 1460, Rate = 3.6,
                        DateCreate = DateTime.Now.AddHours(4) },
            new Product { Name = "Ведьмак", Description = "Фэнтези книга по вселенной ведьмака",
                        Price = 24, Category = "Фантастика", Language = "Русский", Age = 18,
                        Author = "Анджей Сапковский", Size = "200x450", PageCount = 234, Rate = 4.5,
                        DateCreate = DateTime.Now.AddHours(1) },
            new Product { Name = "Ведьмак", Description = "Фэнтези книга по вселенной ведьмака",
                        Price = 234, Category = "Драма", Language = "Русский", Age = 10,
                        Author = "Анджей Сапковский", Size = "200x450", PageCount = 2525, Rate = 4.3,
                        DateCreate = DateTime.Now.AddHours(2) },
            new Product { Name = "Ведьмак", Description = "Фэнтези книга по вселенной ведьмака",
                        Price = 423, Category = "Наука", Language = "Русский", Age = 14,
                        Author = "Анджей Сапковский", Size = "200x450", PageCount = 1212, Rate = 7.8,
                        DateCreate = DateTime.Now.AddHours(2) },
            new Product { Name = "Ведьмак", Description = "Фэнтези книга по вселенной ведьмака",
                        Price = 434, Category = "Детективы", Language = "Русский", Age = 12,
                        Author = "Анджей Сапковский", Size = "200x450", PageCount = 4535, Rate = 9.5,
                        DateCreate = DateTime.Now.AddHours(5) },
            new Product { Name = "Ведьмак", Description = "Фэнтези книга по вселенной ведьмака",
                        Price = 275, Category = "Эпос", Language = "Русский", Age = 16,
                        Author = "Анджей Сапковский", Size = "200x450", PageCount = 1214, Rate = 6.7,
                        DateCreate = DateTime.Now.AddHours(1) },
            new Product { Name = "Ведьмак", Description = "Фэнтези книга по вселенной ведьмака",
                        Price = 500, Category = "Фэнтези", Language = "Русский", Age = 50,
                        Author = "Анджей Сапковский", Size = "200x450", PageCount = 1460, Rate = 3.6,
                        DateCreate = DateTime.Now.AddHours(4) },
            new Product { Name = "Ведьмак", Description = "Фэнтези книга по вселенной ведьмака",
                        Price = 24, Category = "Фантастика", Language = "Русский", Age = 18,
                        Author = "Анджей Сапковский", Size = "200x450", PageCount = 234, Rate = 4.5,
                        DateCreate = DateTime.Now.AddHours(1) },
            new Product { Name = "Ведьмак", Description = "Фэнтези книга по вселенной ведьмака",
                        Price = 234, Category = "Драма", Language = "Русский", Age = 10,
                        Author = "Анджей Сапковский", Size = "200x450", PageCount = 2525, Rate = 4.3,
                        DateCreate = DateTime.Now.AddHours(2) },
            new Product { Name = "Ведьмак", Description = "Фэнтези книга по вселенной ведьмака",
                        Price = 423, Category = "Наука", Language = "Русский", Age = 14,
                        Author = "Анджей Сапковский", Size = "200x450", PageCount = 1212, Rate = 7.8,
                        DateCreate = DateTime.Now.AddHours(2) },
            new Product { Name = "Ведьмак", Description = "Фэнтези книга по вселенной ведьмака",
                        Price = 434, Category = "Детективы", Language = "Русский", Age = 12,
                        Author = "Анджей Сапковский", Size = "200x450", PageCount = 4535, Rate = 9.5,
                        DateCreate = DateTime.Now.AddHours(5) },
            new Product { Name = "Ведьмак", Description = "Фэнтези книга по вселенной ведьмака",
                        Price = 275, Category = "Эпос", Language = "Русский", Age = 16,
                        Author = "Анджей Сапковский", Size = "200x450", PageCount = 1214, Rate = 6.7,
                        DateCreate = DateTime.Now.AddHours(1) }
        }.AsQueryable<Product>();
    }
}
